### ISSUE TITLE
Evaluate if data.gov.au dataset is better

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/logan#1]
http://data.gov.au/dataset/cf5cf085-85ca-42ea-b453-54c171ff8149

**Comment by henare** [comment]
:headdesk:

![selection_001](https://cloud.githubusercontent.com/assets/48945/25216836/cece3992-25e7-11e7-84d8-9a59141702df.png)

**Comment by henare** [comment]
Latest data in the CSV is from 2015 so [it's a joke, like the Ballarat one](https://github.com/planningalerts-scrapers/ballarat/issues/1#issuecomment-295597973).
